apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.app.name }}-config
data:
  ELASTICSEARCH_HOST: "http://{{ .Values.elasticsearch.name }}:{{ .Values.elasticsearch.port }}"
  ELASTICSEARCH_INDEX: "city-populations"
