apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.elasticsearch.name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.elasticsearch.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.elasticsearch.name }}
    spec:
      containers:
        - name: elasticsearch
          image: "{{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}"
          ports:
            - containerPort: {{ .Values.elasticsearch.port }}
          
          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

          env:
            - name: discovery.type
              value: single-node
            - name: xpack.security.enabled
              value: "false"
            - name: ES_JAVA_OPTS     # Added after OOMKilled
              value: "-Xms128m -Xmx128m"
